// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(MarcaAutoDbContext))]
    partial class MarcaAutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.MarcaAuto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("marcaAutosDb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b09e72d-755b-40a1-80e0-8e0c847ece0e"),
                            marca = "Subaru",
                            pais = "Japon",
                            url = "https://www.worldsubaru.com/"
                        },
                        new
                        {
                            Id = new Guid("b7b6b47c-ec42-4f4c-871f-fd3330e919f5"),
                            marca = "BMW",
                            pais = "Alemania",
                            url = "https://www.bmw.com/en/index.html"
                        },
                        new
                        {
                            Id = new Guid("706ba802-3444-44eb-a39a-404d4a709245"),
                            marca = "Ford",
                            pais = "Estados Unidos",
                            url = "https://www.ford.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
